spring:
  profiles.active: local
productName: TicketExpress
---
spring:
  profiles: dev
server.port: 8080
salesforce:
  url: https://sabre--tncommdp3.cs8.my.salesforce.com/services
  username: ${USERNAME}
  password: ${PASSWORD}
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}